include: package:lints/recommended.yaml

analyzer:
  exclude: [bin/*.g.dart]

# https://dart.dev/tools/analysis
# https://dart.dev/tools/linter-rules/all
linter:
  rules:
    prefer_single_quotes: true
    unnecessary_this: false
    file_names: false
