name: my_dart
description: my_dart package project
version: 2025.420.702
homepage:
repository: https://github.com/dart-pkg/my_dart

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  output: ^1.0.1
  sys: ^2025.420.1441
  winsys: ^2025.420.1442

dev_dependencies:
  lints: ^5.1.1
  embed: ^1.4.1
  build_runner: ^2.4.15
