# これはパブスペックヤムルです！
name: dart
description: A sample command-line application
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  ffi: ^2.1.4
  path: ^1.9.1
  win32: ^5.12.0
  #misc:
  #  path: ../misc
  misc:
    git:
      url: https://github.com/lang-library/dart-misc
      ref: 2025.0416.1917
  embed_annotation: ^1.2.2
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  embed: ^1.4.1
  #lints: ^5.1.1
  lints: ^6.0.0
  test: ^1.24.0
